<?php
/**
 * Generated by the admin panel — do not edit by hand.
 *
 * Written 2026-08-16 00:43:45. The editable copy lives in the
 * database; this file exists so public pages never have to query it.
 * Deleting it makes the site fall back to data/about.php.
 */

return array(
  'eyebrow' => 'About Us',
  'heading' => 'Your Partner for Better SHE Performance',
  'pillars' =>
    array(
      0 => 'Practical Solutions',
      1 => 'Expert Support',
      2 => 'Reliable Service',
      3 => 'Long-Term Partnership',
    ),
  'lead' => 'We help organizations create safer workplaces, strengthen workforce competency, and build more effective SHE practices.',
  'paragraphs' =>
    array(
      0 => 'Jasa General Consultant provides SHE consulting, competency training, assessment, and procurement services tailored to different operational and business needs.',
      1 => 'We support clients in managing workplace risks, strengthening employee capability, and improving SHE implementation through practical solutions and experienced professionals.',
      2 => 'For competency training and assessment, we also collaborate with accredited professional certification institutions aligned with applicable national and international standards.',
    ),
  'portrait' =>
    array(
      'image' => 'images/bg_director_new.png',
      'name' => 'Ir. Heru Andrianto',
      'role' => 'Commissioner',
    ),
);
