<?php
/**
 * Generated by the admin panel — do not edit by hand.
 *
 * Written 2026-08-16 00:43:45. The editable copy lives in the
 * database; this file exists so public pages never have to query it.
 * Deleting it makes the site fall back to data/centers.php.
 */

return array (
  0 => 
  array (
    'name' => 'Competency Assessment Center (TUK)',
    'image' => 'images/train2.png',
    'alt' => 'Area praktik assessment kompetensi di Bandung',
    'address' => 
    array (
      0 => 'Jl. Mekar Makmur No. 38 A',
      1 => 'Komplek Istana Mekar Wangi',
      2 => 'Bandung West Java, 40227',
    ),
  ),
  1 => 
  array (
    'name' => 'Competency Assessment Center (TUK)',
    'image' => 'images/train1.png',
    'alt' => 'Ruang kelas assessment kompetensi di Jakarta Selatan',
    'address' => 
    array (
      0 => 'Jl. Cikoko Timur Raya No.43,',
      1 => 'Kelurahan;, Cikoko, Kec. Pancoran Kota',
      2 => 'Jakarta Selatan',
      3 => 'Daerah Khusus Ibukota Jakarta 12770',
    ),
  ),
  2 => 
  array (
    'name' => 'RA Premiere',
    'image' => 'images/train3.png',
    'alt' => 'Training room at Bangun Negeri Centre',
    'address' => 
    array (
      0 => 'Jl. Intan No.25 1, RT.1/RW.2,',
      1 => 'Cilandak Barat, Kec. Cilandak, Kota Jakarta Selatan',
      2 => 'DKI Jakarta 12430',
    ),
  ),
);
