<?php
/**
 * Generated by the admin panel — do not edit by hand.
 *
 * Written 2026-08-16 00:43:45. The editable copy lives in the
 * database; this file exists so public pages never have to query it.
 * Deleting it makes the site fall back to data/gallery.php.
 */

return array (
  0 => 
  array (
    'file' => 'galeri/Image.png',
    'caption' => '',
    'width' => 139,
    'height' => 201,
  ),
  1 => 
  array (
    'file' => 'galeri/Image-1.png',
    'caption' => '',
    'width' => 618,
    'height' => 201,
  ),
  2 => 
  array (
    'file' => 'galeri/Image-2.png',
    'caption' => '',
    'width' => 202,
    'height' => 201,
  ),
  3 => 
  array (
    'file' => 'galeri/Image-3.png',
    'caption' => '',
    'width' => 415,
    'height' => 201,
  ),
  4 => 
  array (
    'file' => 'galeri/Image-4.png',
    'caption' => '',
    'width' => 419,
    'height' => 201,
  ),
  5 => 
  array (
    'file' => 'galeri/Image-5.png',
    'caption' => '',
    'width' => 283,
    'height' => 201,
  ),
  6 => 
  array (
    'file' => 'galeri/Image-6.png',
    'caption' => '',
    'width' => 533,
    'height' => 200,
  ),
  7 => 
  array (
    'file' => 'galeri/Image-7.png',
    'caption' => '',
    'width' => 137,
    'height' => 201,
  ),
  8 => 
  array (
    'file' => 'galeri/Image-8.png',
    'caption' => '',
    'width' => 618,
    'height' => 201,
  ),
  9 => 
  array (
    'file' => 'galeri/Image-9.png',
    'caption' => '',
    'width' => 283,
    'height' => 201,
  ),
  10 => 
  array (
    'file' => 'galeri/Image-10.png',
    'caption' => '',
    'width' => 173,
    'height' => 200,
  ),
  11 => 
  array (
    'file' => 'galeri/Image-11.png',
    'caption' => '',
    'width' => 282,
    'height' => 201,
  ),
  12 => 
  array (
    'file' => 'galeri/Image-12.png',
    'caption' => '',
    'width' => 328,
    'height' => 200,
  ),
  13 => 
  array (
    'file' => 'galeri/Image-13.png',
    'caption' => '',
    'width' => 283,
    'height' => 201,
  ),
  14 => 
  array (
    'file' => 'galeri/Image-14.png',
    'caption' => '',
    'width' => 173,
    'height' => 200,
  ),
  15 => 
  array (
    'file' => 'galeri/Image-15.png',
    'caption' => '',
    'width' => 283,
    'height' => 201,
  ),
  16 => 
  array (
    'file' => 'galeri/Image-16.png',
    'caption' => '',
    'width' => 282,
    'height' => 201,
  ),
);
