<?php
/**
 * Generated by the admin panel — do not edit by hand.
 *
 * Written 2026-08-16 00:43:45. The editable copy lives in the
 * database; this file exists so public pages never have to query it.
 * Deleting it makes the site fall back to data/jobs.php.
 */

return array (
  0 => 
  array (
    'title' => 'Safety Leadership Trainer',
    'urgent' => true,
    'type' => 'Contract',
    'location' => 'Jakarta, DKI Jakarta',
    'banner' => 'images/career-banner.jpg',
    'summary' => 'We are looking for an experienced Safety Leadership Trainer to facilitate training using immersive learning, experiential learning, and interactive methods to strengthen safety culture, safety leadership, and behavioral change at the Tangguh UCC Project.',
    'quals' => 
    array (
      0 => 
      array (
        'text' => '5–10 years of experience as a trainer, facilitator, or training consultant in Occupational Health and Safety (OHS), Safety Leadership, Human Performance, or a related field.',
        'items' => 
        array (
        ),
      ),
      1 => 
      array (
        'text' => 'Experience facilitating training for:',
        'items' => 
        array (
          0 => 'Supervisors',
          1 => 'Superintendents',
          2 => 'Managers',
          3 => 'Senior Leaders',
        ),
      ),
      2 => 
      array (
        'text' => 'Able to deliver and facilitate training in:',
        'items' => 
        array (
          0 => 'Indonesian',
          1 => 'English (minimum professional proficiency for presentations and classroom facilitation)',
        ),
      ),
      3 => 
      array (
        'text' => 'Experienced in using learning methods such as:',
        'items' => 
        array (
          0 => 'Immersive Learning',
          1 => 'Experiential Learning',
          2 => 'Scenario-Based Learning',
          3 => 'Gamification',
          4 => 'Interactive Workshops',
          5 => 'Simulation & Role Play',
        ),
      ),
      4 => 
      array (
        'text' => 'Proficient in using and developing:',
        'items' => 
        array (
          0 => 'Interactive Training Kits',
          1 => 'Safety Learning Simulations',
          2 => 'Immersive Learning Tools',
          3 => 'Facilitation Tools and Learning Media',
        ),
      ),
      5 => 
      array (
        'text' => 'Based in Jakarta or surrounding areas.',
        'items' => 
        array (
        ),
      ),
    ),
  ),
);
