<?php
/**
 * Generated by the admin panel — do not edit by hand.
 *
 * Written 2026-08-16 00:43:45. The editable copy lives in the
 * database; this file exists so public pages never have to query it.
 * Deleting it makes the site fall back to data/locations.php.
 */

return array (
  'frame' => 
  array (
    'lng_min' => 94.5,
    'lng_max' => 141.5,
    'lat_min' => -11.3,
    'lat_max' => 6.3,
  ),
  'pins' => 
  array (
    0 => 
    array (
      'name' => 'Batam',
      'lat' => 1.0456,
      'lng' => 104.0305,
      'place' => 'right',
      'dx' => 1.1,
      'dy' => 0.0,
    ),
    1 => 
    array (
      'name' => 'Palembang',
      'lat' => -2.9761,
      'lng' => 104.7754,
      'place' => 'left',
      'dx' => 1.1,
      'dy' => 0.0,
    ),
    2 => 
    array (
      'name' => 'Cilegon',
      'lat' => -6.0175,
      'lng' => 106.0538,
      'place' => 'left',
      'dx' => 1.1,
      'dy' => 0.0,
    ),
    3 => 
    array (
      'name' => 'Jakarta',
      'lat' => -6.2088,
      'lng' => 106.8456,
      'place' => 'center',
      'dx' => 0.0,
      'dy' => 2.16,
    ),
    4 => 
    array (
      'name' => 'Balongan',
      'lat' => -6.3667,
      'lng' => 108.3833,
      'place' => 'center',
      'dx' => -1.24,
      'dy' => -2.16,
    ),
    5 => 
    array (
      'name' => 'Cilacap',
      'lat' => -7.7269,
      'lng' => 109.01,
      'place' => 'center',
      'dx' => 0.0,
      'dy' => 2.16,
    ),
    6 => 
    array (
      'name' => 'Bojonegoro',
      'lat' => -7.1502,
      'lng' => 111.8817,
      'place' => 'center',
      'dx' => 0.0,
      'dy' => -2.16,
    ),
    7 => 
    array (
      'name' => 'Tuban',
      'lat' => -6.8976,
      'lng' => 112.0648,
      'place' => 'center',
      'dx' => 0.0,
      'dy' => -3.88,
    ),
    8 => 
    array (
      'name' => 'Surabaya',
      'lat' => -7.2575,
      'lng' => 112.7521,
      'place' => 'right',
      'dx' => 1.1,
      'dy' => 0.0,
    ),
    9 => 
    array (
      'name' => 'Makassar',
      'lat' => -5.1477,
      'lng' => 119.4327,
      'place' => 'right',
      'dx' => 1.1,
      'dy' => 0.0,
    ),
    10 => 
    array (
      'name' => 'Balikpapan',
      'lat' => -1.2379,
      'lng' => 116.8529,
      'place' => 'right',
      'dx' => 1.1,
      'dy' => 0.0,
    ),
    11 => 
    array (
      'name' => 'Sorong',
      'lat' => -0.8762,
      'lng' => 131.2558,
      'place' => 'left',
      'dx' => 1.1,
      'dy' => 0.0,
    ),
  ),
);
