<?php
/**
 * Generated by the admin panel — do not edit by hand.
 *
 * Written 2026-08-16 00:43:45. The editable copy lives in the
 * database; this file exists so public pages never have to query it.
 * Deleting it makes the site fall back to data/partners.php.
 */

return array (
  0 => 
  array (
    'name' => 'bp',
    'file' => 'images/partner3.png',
  ),
  1 => 
  array (
    'name' => 'CBT — Care, Leadership & Culture',
    'file' => 'images/partner2.png',
  ),
  2 => 
  array (
    'name' => 'JGC',
    'file' => 'images/partner1.png',
  ),
);
