<?php
/**
 * Generated by the admin panel — do not edit by hand.
 *
 * Written 2026-08-16 00:43:45. The editable copy lives in the
 * database; this file exists so public pages never have to query it.
 * Deleting it makes the site fall back to data/services.php.
 */

return array (
  0 => 
  array (
    'title' => 'Consultancy',
    'icon' => 'presentation',
    'items' => 
    array (
      0 => 
      array (
        0 => 'HSE Management Systems — SMK3, SMKM Migas,',
        1 => 'SMKP, CSMS, ISO 45001/9001/14001/29001, PSM',
      ),
      1 => 'SOP, forms & practical operational tools',
      2 => 'Risk & gap assessment · Safety culture maturity',
      3 => 'Roadmap implementation aligned with industry best practice',
      4 => 'Organizational Development',
      5 => 'Technical and NonTechnical Assessment & Coaching',
      6 => 'Training Need Analysis',
      7 => 'SHE Inspection',
    ),
  ),
  1 => 
  array (
    'title' => 'Competency Training & Assessment',
    'icon' => 'graduation-cap',
    'items' => 
    array (
      0 => 'Occupational Health & Safety Management System',
      1 => 'Technical SHE',
      2 => 'Safety Culture',
      3 => 'Aviation & Helicopter',
      4 => 'Driving & Riding',
      5 => 'Offshore & Survival',
      6 => 
      array (
        0 => 'Marine,',
        1 => 'Professional Certification (Migas,',
        2 => 'Kemenakertrans RI, ESDM, ISO, BNSP,',
        3 => 'Kemenhub, NIOSH, NEBOSH)',
      ),
    ),
    'topics' => 
    array (
      0 => 'Introduction to HSE',
      1 => 'Safety Culture',
      2 => 'HSE Roles and Responsibilities',
      3 => 'Hazard Identification',
      4 => 'Risk Assessment (HIRARC)',
      5 => 'Incident and Near Miss Reporting',
      6 => 'Use of Personal Protective Equipment (PPE)',
      7 => 'Workplace Housekeeping (5S)',
      8 => 'Toolbox Talk / Safety Briefing',
      9 => 'Emergency Preparedness',
      10 => 'Permit to Work',
      11 => 'Working at Heights',
      12 => 'Energy Isolation (LOTO)',
      13 => 'Gas Detection',
      14 => 'Line of Fire',
      15 => 'Working at Height Procedure',
      16 => 'Safe Driving and Journey Management',
      17 => 'Bypass Critical Protection Procedure',
      18 => 'Confined Space Entry',
      19 => 'Behavior Based Safety',
      20 => 'Root Cause Analysis (RCA)',
      21 => 'Incident Investigation',
      22 => 'Management of Change (MOC)',
      23 => 'Contractor HSE Management',
      24 => 'Safety Leadership',
      25 => 'Safety Observation and Intervention',
      26 => 'Lifting and Rigging Safety',
      27 => 'Fall Protection',
      28 => 'Fire Prevention and Firefighting',
      29 => 'Emergency Drill Execution',
      30 => 'Chemical Hazard Management',
      31 => 'Heat Stress Management',
      32 => 'Ergonomics in the Workplace',
      33 => 'Noise and Vibration Exposure',
      34 => 'Occupational Hygiene',
      35 => 'Fatigue Risk Management',
      36 => 'Repetitive Stress Injury Prevention',
      37 => 'Safety Critical Elements (SECE)',
      38 => 'Major Accident Hazard (MAH)',
      39 => 'HSE Risk Management',
      40 => 'Defensive Driving',
      41 => 'Spill Prevention and Control',
      42 => 'Internal HSE Audit',
      43 => 'Environmental Management',
      44 => 'Emergency Response',
      45 => 'HSE Performance Monitoring',
      46 => 'HSE Training and Competency Development',
      47 => 'HSE Digitalization',
      48 => 'HSE Career Mentoring',
      49 => 'HSE in Oil & Gas Industry',
    ),
  ),
  2 => 
  array (
    'title' => 'Digitalisation',
    'icon' => 'monitor',
    'items' => 
    array (
      0 => 'Digital Permit to Work — role-based approvals & close-out',
      1 => 'Incident & observation reporting (unsafe acts/conditions)',
      2 => 'Dashboards · KPI · Action tracking · Journey Management',
      3 => 'Mobile-friendly inspections, audits, MCU monitoring',
    ),
  ),
);
