<?php
/**
 * Generated by the admin panel — do not edit by hand.
 *
 * Written 2026-08-16 00:43:45. The editable copy lives in the
 * database; this file exists so public pages never have to query it.
 * Deleting it makes the site fall back to data/settings.php.
 */

return array (
  'about_block.eyebrow' => 'About Us',
  'about_block.heading' => 'Your Partner for Better SHE Performance',
  'about_block.lead' => 'We help organizations create safer workplaces, strengthen workforce competency, and build more effective SHE practices.',
  'about_block.paragraphs' => 
  array (
    0 => 'Jasa General Consultant provides SHE consulting, competency training, assessment, and procurement services tailored to different operational and business needs.',
    1 => 'We support clients in managing workplace risks, strengthening employee capability, and improving SHE implementation through practical solutions and experienced professionals.',
    2 => 'For competency training and assessment, we also collaborate with accredited professional certification institutions aligned with applicable national and international standards.',
  ),
  'about_block.pillars' => 
  array (
    0 => 'Practical Solutions',
    1 => 'Expert Support',
    2 => 'Reliable Service',
    3 => 'Long-Term Partnership',
  ),
  'about_block.portrait.image' => 'images/Commisioner.png',
  'about_block.portrait.name' => 'Ir. Heru Andrianto',
  'about_block.portrait.role' => 'Commissioner',
  'about.hero.title' => 'About Us',
  'about.mission.heading' => 'Mission',
  'about.mission.items' => 
  array (
    0 => 'Deliver practical SHE consulting and management system development',
    1 => 'Build safety behaviour and culture through quality training',
    2 => 'Ensure workforce competency through professional assessment',
    3 => 'Support operations with reliable SHE procurement',
    4 => 'Build long-term partnerships based on trust and results',
  ),
  'about.story.body' => 'Established in 2018, PT Jasa General Consultant SHE has grown into a comprehensive SHE consulting, competency training, assessment, and procurement partner serving industries across Indonesia.',
  'about.story.heading' => 'Our Story',
  'about.values.heading' => 'Our Values',
  'about.values.items' => 
  array (
    0 => 
    array (
      'text' => 'Integrity',
      'items' => 
      array (
        0 => 'We uphold the highest standards of honesty and ethical conduct in everything we do.',
      ),
    ),
    1 => 
    array (
      'text' => 'Excellence',
      'items' => 
      array (
        0 => 'We strive for excellence in delivery, client service, and professional standards.',
      ),
    ),
    2 => 
    array (
      'text' => 'Impact',
      'items' => 
      array (
        0 => 'We measure success by the real, tangible improvements we create for our clients.',
      ),
    ),
    3 => 
    array (
      'text' => 'Collaboration',
      'items' => 
      array (
        0 => 'We work alongside our clients as partners, not just service providers.',
      ),
    ),
  ),
  'about.vision.body' => 'To be a trusted SHE partner recognized for delivering measurable impact on safety performance and workforce competency.',
  'about.vision.heading' => 'Vision',
  'careers.empty' => 'There are no openings at the moment. Send your CV to {email} and we will keep it on file for future roles.',
  'careers.explore.heading' => 'Explore Career Opportunities',
  'careers.hero.caption' => 'Grow with us, make an impact, and build a safer future as part of our team.',
  'careers.hero.lead' => 'Join PT Jasa General ConsultantSHE and grow your career while contributing to safer, healthier, and more responsible workplaces across industries.',
  'careers.hero.points' => 
  array (
    0 => 'Grow through real-world SHE projects',
    1 => 'Learn from experienced industry professionals',
    2 => 'Develop technical and professional skills',
    3 => 'Work with teams across diverse industries',
  ),
  'careers.hero.title' => 'Build Your Career. Help Shape Safer Workplaces.',
  'careers.openings.heading' => 'Current Openings',
  'careers.openings.lead' => 'Explore our current career opportunities and find the role that fits your expertise.',
  'clients.hero.lead' => 'Supporting organizations across Indonesia since 2018',
  'clients.hero.title' => 'Our Clients',
  'clients.industries' => 
  array (
    0 => 'Oil & Gas',
    1 => 'Manufacturing',
    2 => 'Mining & Energy',
    3 => 'Construction',
    4 => 'Healthcare',
    5 => 'Education',
    6 => 'Government',
    7 => 'Transportation',
  ),
  'clients.sectors.heading' => 'Sectors We Serve',
  'clients.trusted.body' => 'We partner with organizations across high-risk sectors including oil & gas, mining, construction, manufacturing, energy, and transportation.',
  'clients.trusted.heading' => 'Trusted Across Industries',
  'contact.hero.lead' => 'Let’s start a conversation about your SHE needs',
  'contact.hero.title' => 'Contact Us',
  'contact.intro.body' => 'Ada pertanyaan tentang layanan kami atau butuh proposal khusus? Kami siap membantu.',
  'contact.intro.heading' => 'Get in Touch',
  'contact.success' => 'Pesan Anda sudah terkirim. Kami akan segera menghubungi Anda.',
  'cta.button' => 'Start a Conversation',
  'cta.heading' => 'Let’s Discuss Your SHE Needs',
  'error404.body' => 'Halaman yang Anda cari tidak ditemukan.',
  'error404.cta' => 'Kembali ke Beranda',
  'error404.title' => '404',
  'footer.rights' => 'All Rights Reserved.',
  'gallery.empty' => 'Belum ada foto yang ditampilkan.',
  'gallery.hero.lead' => 'A look at our consulting sessions, competency assessments, and training programmes delivered across Indonesia.',
  'gallery.hero.title' => 'Moments From the Field & Classroom',
  'home.centers.heading' => 'Our Training & Assessment Centers',
  'home.gallery.cta' => 'View Full Gallery',
  'home.hero.cta_primary' => 'Discuss Your SHE Needs',
  'home.hero.cta_secondary' => 'Explore Our Services',
  'home.hero.lead' => 'We help organizations strengthen Safety, Health, and Environment (SHE) practices through consulting, competency development, assessment, and procurement support.',
  'home.hero.title' => 'Building Safer Workplaces, Stronger Teams, and Better Operations',
  'home.partners.eyebrow' => 'Trusted Across Industries',
  'home.partners.heading' => 'Supporting Organizations Across Indonesia',
  'home.presence.heading' => 'Local Presence, Wider Support',
  'home.presence.lead' => 'Our presence across multiple locations in Indonesia enables faster coordination, better access to local resources, and more responsive support for clients across regions and industries.',
  'home.services.cta' => 'Talk to Our Team',
  'home.services.footnote' => 'Need help choosing the right service?',
  'home.services.heading' => 'Our Services',
  'map.lat_max' => 6.3,
  'map.lat_min' => -11.3,
  'map.lng_max' => 141.5,
  'map.lng_min' => 94.5,
  'nav.cta' => 'Discuss Your SHE Needs',
  'nav.items' => 
  array (
    0 => 
    array (
      'text' => 'Home',
      'items' => 
      array (
        0 => '/',
      ),
    ),
    1 => 
    array (
      'text' => 'About Us',
      'items' => 
      array (
        0 => '/#about',
      ),
    ),
    2 => 
    array (
      'text' => 'Services',
      'items' => 
      array (
        0 => '/#services',
      ),
    ),
    3 => 
    array (
      'text' => 'Career',
      'items' => 
      array (
        0 => '/careers',
      ),
    ),
    4 => 
    array (
      'text' => 'Contact',
      'items' => 
      array (
        0 => '/#contact',
      ),
    ),
  ),
  'seo.about.description' => 'PT Jasa General Consultant SHE is an Indonesian consultancy for HSE competency assessment, safety training, and Safety, Health, and Environment management.',
  'seo.about.title' => 'About Us - PT Jasa General Consultant SHE',
  'seo.careers.description' => 'Open positions at PT Jasa General Consultant SHE. Build your career with a team of HSE competency assessment, safety leadership, and SHE training professionals.',
  'seo.careers.title' => 'Career - PT Jasa General Consultant SHE',
  'seo.clients.description' => 'Companies that trust PT Jasa General Consultant SHE for HSE competency assessment, safety training, and SHE consulting across Indonesia.',
  'seo.clients.title' => 'Our Clients - PT Jasa General Consultant SHE',
  'seo.contact.description' => 'Talk to PT Jasa General Consultant SHE in Jakarta about HSE competency assessment, SHE consulting, and safety training for your operations.',
  'seo.contact.title' => 'Contact Us - PT Jasa General Consultant SHE',
  'seo.gallery.description' => 'Documentation of HSE competency assessment, training, and consulting work by PT Jasa General Consultant SHE across Indonesia.',
  'seo.gallery.title' => 'Gallery - PT Jasa General Consultant SHE',
  'seo.home.description' => 'PT Jasa General Consultant SHE delivers HSE competency assessment, SHE consulting, competency training, and procurement support for industries across Indonesia.',
  'seo.home.title' => 'PT Jasa General Consultant SHE - HSE Competency Assessment',
  'seo.services.description' => 'HSE competency assessment, SHE consulting, competency development and training, and SHE procurement support from PT Jasa General Consultant SHE.',
  'seo.services.title' => 'Our Services - PT Jasa General Consultant SHE',
  'services.hero.lead' => 'Consulting, competency development, assessment, and procurement support',
  'services.hero.title' => 'Our Services',
  'services.topics.heading' => 'Training Topics',
  'site.address_lines' => 
  array (
    0 => 'Pamulang Permai 1 Blok CX01/10 no 1',
    1 => 'Pamulang Barat - Tangerang Selatan',
  ),
  'site.address.country' => 'ID',
  'site.address.locality' => 'Cilandak Barat, Kec. Cilandak, Kota Jakarta Selatan',
  'site.address.postal' => '12430',
  'site.address.region' => 'Daerah Khusus Ibukota Jakarta',
  'site.address.street' => 'RA Premiere, Jl. Intan No.25 1, RT.1/RW.2',
  'site.careers_email' => 'generalconsultant@jasagenshe.com',
  'site.description' => 'PT Jasa General Consultant SHE helps organizations strengthen Safety, Health, and Environment practices through consulting, competency development, assessment, and procurement support.',
  'site.email' => 'generalconsultant@jasagenshe.com',
  'site.instagram' => 'general_consultantshe',
  'site.keywords' => 
  array (
    0 => 'HSE Competency Assessment',
    1 => 'SHE consultant Indonesia',
    2 => 'competency assessment center',
    3 => 'TUK LSP K3',
    4 => 'safety leadership training',
    5 => 'HSE training provider Jakarta',
    6 => 'K3 consulting',
    7 => 'safety health environment consultant',
  ),
  'site.name' => 'PT Jasa General Consultant SHE',
  'site.og_image' => 'images/og-image.jpg',
  'site.phone' => '+62 859 7755 5933',
  'site.short_name' => 'PT Jasa General ConsultantSHE',
  'site.tagline' => 'Building Safer Workplaces, Stronger Teams, and Better Operations',
  'site.whatsapp' => '6285977555933',
  'site.whatsapp_template' => 'Halo PT Jasa General Consultant SHE, saya tertarik dengan layanan perusahaan Anda. Boleh minta informasi lebih lanjut?',
  'site.year_founded' => 2018,
);
